### ISSUE TITLE
Code block CSS - margin-bottom

### ISSUE THREAD

**Issue by kevinjalbert** [jimbobbennett/FauxGhost#3]
The code blocks seem to be missing a `margin-bottom` value. The following is from your blog screenshots are from your blog:
### Original

Notice the lack of vertical spacing after the code block to the start of the next paragraph.

![without margin-bottom](https://dl.dropbox.com/s/xye1bh0e7p3ucjd/Screenshot%202015-05-10%2016.25.11.png)
### With `margin-bottom: 1.25rem`

Notice that the vertical spacing after the code block to the start of the next paragraph now falls in line with the others.

![with margin-bottom](https://dl.dropbox.com/s/mgerkpl6svexoco/Screenshot%202015-05-10%2016.28.22.png)

**Comment by jimbobbennett** [comment]
Good spot!  I did notice it looked a bit odd but never got round to fixing it!  So much to do, so little time!

Can you raise a PR for the fix?

**Comment by kevinjalbert** [comment]
Fixed in #4
